package com.glucotwin.domain.insight;

import java.time.Instant;
import java.util.Objects;

/**
 * Immutable domain value object representing the output of the LLM explanation step.
 *
 * <p>Safety rules enforced here:
 * <ul>
 *   <li>The {@code explanation} is plain natural-language text generated by the LLM.
 *   <li>It must never be treated as a medical prediction, diagnosis, or recommendation.
 *   <li>It is always displayed with the existing {@code safetyDisclaimer}.
 *   <li>No numeric clinical values (spikeProbability, riskCategory) are sourced from here —
 *       those always come from the deterministic XGBoost pipeline.
 * </ul>
 *
 * <p>Phase 13 — observability metadata only, not clinical evidence.
 */
public record InsightExplanationResult(
        /** LLM-generated explanation text. Never null; may be empty on fallback. */
        String explanation,
        /** The model that generated the explanation (e.g. "gpt-4o-mini"). */
        String modelId,
        /** Approximate prompt tokens used, for cost/observability tracking. */
        int promptTokens,
        /** Approximate completion tokens returned. */
        int completionTokens,
        /** UTC timestamp of generation. */
        Instant generatedAt) {

    public InsightExplanationResult {
        Objects.requireNonNull(explanation, "explanation must not be null");
        Objects.requireNonNull(generatedAt, "generatedAt must not be null");
        modelId         = modelId != null ? modelId : "unknown";
        if (promptTokens < 0)    promptTokens    = 0;
        if (completionTokens < 0) completionTokens = 0;
    }

    /** Convenience factory for a failed/skipped explanation. */
    public static InsightExplanationResult unavailable() {
        return new InsightExplanationResult("", "none", 0, 0, Instant.now());
    }

    public boolean hasContent() {
        return !explanation.isBlank();
    }
}
